export interface Episode {
  slug: string
  title: string
  company: string
  duration: string
  description: string
  shortDescription?: string
  season: string | number
  episode: string | number
  date: string
  coverImage: string
  youtubeId?: string
  spotifyUrl?: string
  applePodcastsUrl?: string
  transcript?: { time: string; text: string }[] | string
  carveOuts?: { person: string; items: string[] }[]
  followUps?: string[]
  sponsors?: { name: string; description: string }[]
}

function generateSlug(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .trim()
}

export const allEpisodes: Episode[] = [
  {
    slug: generateSlug("10 Years of Acquired (with Michael Lewis)"),
    title: "10 Years of Acquired (with Michael Lewis)",
    company: "10 Years of Acquired",
    duration: "Special",
    description:
      "Celebrating a decade of Acquired with legendary author Michael Lewis. We reflect on ten years of telling the stories behind the world's greatest companies, and Michael shares insights from his legendary career in narrative nonfiction.",
    shortDescription: "Reflect on ten years of Acquired with Michael Lewis.",
    season: "Special",
    episode: "",
    date: "December 14, 2025",
    coverImage: "/10-years-acquired-podcast-michael-lewis-celebratio.jpg",
    youtubeId: "dQw4w9WgXcQ",
    spotifyUrl: "https://open.spotify.com/show/acquired",
    applePodcastsUrl: "https://podcasts.apple.com/podcast/acquired",
    transcript: [
      { time: "00:00", text: "Welcome to a very special episode of Acquired." },
      { time: "00:15", text: "Today we're celebrating ten years of this podcast." },
      { time: "00:30", text: "And we have a very special guest - Michael Lewis." },
      { time: "01:00", text: "Michael, thank you so much for being here with us." },
      { time: "01:15", text: "It's great to be here. I've been a fan of the show for years." },
    ],
    carveOuts: [
      { person: "Ben Gilbert", items: ["The Premonition by Michael Lewis", "Arc Browser"] },
      { person: "David Rosenthal", items: ["Going Infinite by Michael Lewis", "Rabbit R1"] },
      { person: "Michael Lewis", items: ["Acquired Podcast", "The making of a new book"] },
    ],
    followUps: [
      "Correction on our TSMC episode regarding wafer pricing",
      "Follow up on the Google antitrust case developments",
    ],
    sponsors: [
      { name: "Pilot", description: "The best bookkeeping and CFO services for startups." },
      { name: "Statsig", description: "Ship faster with feature flags and experimentation." },
      { name: "Crusoe", description: "The clean compute cloud." },
    ],
  },
  {
    slug: generateSlug("The Insane Productivity of Andrew Ross Sorkin"),
    title: "The Insane Productivity of Andrew Ross Sorkin",
    company: "Andrew Ross Sorkin",
    duration: "ACQ2",
    description:
      "How the CNBC anchor, NYT columnist, and DealBook founder maintains insane productivity while running multiple media properties and writing bestselling books.",
    shortDescription: "Discuss Andrew Ross Sorkin's productivity secrets.",
    season: "ACQ2",
    episode: "",
    date: "December 7, 2025",
    coverImage: "/andrew-ross-sorkin-cnbc-journalist-suit.jpg",
    youtubeId: "dQw4w9WgXcQ",
    spotifyUrl: "https://open.spotify.com/show/acquired",
    applePodcastsUrl: "https://podcasts.apple.com/podcast/acquired",
    transcript: [
      { time: "00:00", text: "Andrew Ross Sorkin might be the most productive person in media." },
      { time: "00:20", text: "He hosts Squawk Box, writes for the Times, runs DealBook..." },
    ],
    carveOuts: [
      { person: "Ben Gilbert", items: ["Too Big to Fail (Book)", "Morning routines"] },
      { person: "David Rosenthal", items: ["DealBook Newsletter", "Financial journalism"] },
    ],
    sponsors: [
      { name: "Pilot", description: "The best bookkeeping and CFO services for startups." },
      { name: "Vanta", description: "Automated security compliance." },
    ],
  },
  {
    slug: generateSlug("Coca-Cola"),
    title: "Coca-Cola",
    company: "Coca-Cola",
    duration: "Fall 2025, Episode 3",
    description:
      "The complete history and strategy of the world's most iconic beverage brand. From a pharmacist's tonic to a global symbol of American culture.",
    shortDescription: "Explore the history of Coca-Cola.",
    season: "Fall 2025",
    episode: "3",
    date: "November 23, 2025",
    coverImage: "/coca-cola-bottle-red-branding-classic.jpg",
    youtubeId: "dQw4w9WgXcQ",
    spotifyUrl: "https://open.spotify.com/show/acquired",
    applePodcastsUrl: "https://podcasts.apple.com/podcast/acquired",
    transcript: [
      { time: "00:00", text: "Coca-Cola is perhaps the most recognized brand on Earth." },
      { time: "00:30", text: "But how did a pharmacist's creation become a global icon?" },
    ],
    carveOuts: [
      { person: "Ben Gilbert", items: ["For God, Country, and Coca-Cola (Book)"] },
      { person: "David Rosenthal", items: ["The Real Thing (Documentary)"] },
    ],
    sponsors: [
      { name: "Statsig", description: "Ship faster with feature flags and experimentation." },
      { name: "Crusoe", description: "The clean compute cloud." },
    ],
  },
  {
    slug: generateSlug("Acquired Live at Radio City Music Hall"),
    title: "Acquired Live at Radio City Music Hall",
    company: "Radio City Live",
    duration: "Special",
    description:
      "Acquired's historic live show at Radio City Music Hall presented by J.P. Morgan. A celebration of business storytelling with 6,000 of our closest friends.",
    shortDescription: "Watch the historic live show at Radio City Music Hall.",
    season: "Special",
    episode: "",
    date: "November 5, 2025",
    coverImage: "/radio-city-music-hall-new-york-city-concert.jpg",
    youtubeId: "dQw4w9WgXcQ",
    spotifyUrl: "https://open.spotify.com/show/acquired",
    applePodcastsUrl: "https://podcasts.apple.com/podcast/acquired",
  },
  {
    slug: generateSlug("Trader Joe's"),
    title: "Trader Joe's",
    company: "Trader Joe's",
    duration: "Fall 2025, Episode 2",
    description:
      "How a quirky grocery chain built one of the most beloved retail brands by doing everything differently from the competition.",
    shortDescription: "Learn how Trader Joe's became a beloved brand.",
    season: "Fall 2025",
    episode: "2",
    date: "October 26, 2025",
    coverImage: "/trader-joes-logo-red-hawaiian-flowers-grocery.jpg",
    youtubeId: "dQw4w9WgXcQ",
    spotifyUrl: "https://open.spotify.com/show/acquired",
    applePodcastsUrl: "https://podcasts.apple.com/podcast/acquired",
    transcript: [
      { time: "00:00", text: "Trader Joe's is unlike any other grocery store." },
      { time: "00:25", text: "Hawaiian shirts, quirky products, and fiercely loyal customers." },
    ],
    carveOuts: [
      {
        person: "Ben Gilbert",
        items: ["Everything Everywhere Daily Podcast", "Trader Joe's Dark Chocolate Peanut Butter Cups"],
      },
      { person: "David Rosenthal", items: ["Build a Second Brain (Book)", "Trader Joe's Mandarin Orange Chicken"] },
    ],
    sponsors: [{ name: "Pilot", description: "The best bookkeeping and CFO services for startups." }],
  },
  {
    slug: generateSlug("Google: The AI Company"),
    title: "Google: The AI Company",
    company: "Google AI",
    duration: "Fall 2025, Episode 1",
    description:
      "Google's transformation into an AI-first company. How the search giant is betting everything on artificial intelligence.",
    shortDescription: "Google's shift towards AI.",
    season: "Fall 2025",
    episode: "1",
    date: "October 5, 2025",
    coverImage: "/google-logo-ai-gradient-colorful-modern.jpg",
    youtubeId: "dQw4w9WgXcQ",
    spotifyUrl: "https://open.spotify.com/show/acquired",
    applePodcastsUrl: "https://podcasts.apple.com/podcast/acquired",
  },
  {
    slug: generateSlug("How to Live in Everyone Else's Future (with Shopify CEO Tobi Lütke)"),
    title: "How to Live in Everyone Else's Future (with Shopify CEO Tobi Lütke)",
    company: "Tobi Lütke",
    duration: "ACQ2",
    description: "Shopify CEO on building for the future and entrepreneurial thinking.",
    shortDescription: "Shopify CEO Tobi Lütke on future-building.",
    season: "ACQ2",
    episode: "",
    date: "September 18, 2025",
    coverImage: "/tobi-lutke-shopify-ceo-speaking-podcast-microphone.jpg",
    youtubeId: "dQw4w9WgXcQ",
    spotifyUrl: "https://open.spotify.com/show/acquired",
    applePodcastsUrl: "https://podcasts.apple.com/podcast/acquired",
  },
  {
    slug: generateSlug("Alphabet Inc."),
    title: "Alphabet Inc.",
    company: "Alphabet",
    duration: "Summer 2025, Episode 4",
    description: "The complete story of Google's parent company and its moonshots.",
    shortDescription: "The story of Alphabet Inc.",
    season: "Summer 2025",
    episode: "4",
    date: "August 26, 2025",
    coverImage: "/alphabet-google-red-logo-corporate.jpg",
    youtubeId: "dQw4w9WgXcQ",
    spotifyUrl: "https://open.spotify.com/show/acquired",
    applePodcastsUrl: "https://podcasts.apple.com/podcast/acquired",
  },
  {
    slug: generateSlug("How is AI Different Than Other Technology Waves"),
    title: "How is AI Different Than Other Technology Waves? (With Bret Taylor and Clay Bavor)",
    company: "AI Technology Waves",
    duration: "ACQ2",
    description: "Sierra co-founders discuss what makes AI fundamentally different.",
    shortDescription: "Sierra co-founders discuss AI's uniqueness.",
    season: "ACQ2",
    episode: "",
    date: "August 18, 2025",
    coverImage: "/bret-taylor-clay-bavor-tech-executives-discussing.jpg",
    youtubeId: "dQw4w9WgXcQ",
    spotifyUrl: "https://open.spotify.com/show/acquired",
    applePodcastsUrl: "https://podcasts.apple.com/podcast/acquired",
  },
  {
    slug: generateSlug("The Jamie Dimon Interview"),
    title: "The Jamie Dimon Interview",
    company: "Jamie Dimon",
    duration: "Summer 2025, Episode 3",
    description: "The legendary JPMorgan CEO on banking, leadership, and America.",
    shortDescription: "Interview with Jamie Dimon on banking and leadership.",
    season: "Summer 2025",
    episode: "3",
    date: "July 16, 2025",
    coverImage: "/jamie-dimon-jpmorgan-ceo-interview-executive.jpg",
    youtubeId: "dQw4w9WgXcQ",
    spotifyUrl: "https://open.spotify.com/show/acquired",
    applePodcastsUrl: "https://podcasts.apple.com/podcast/acquired",
  },
  {
    slug: generateSlug("Google: The Origin of Search"),
    title: "Google: The Origin of Search",
    company: "Google Search",
    duration: "Summer 2025, Episode 2",
    description: "How Larry and Sergey built the world's most important website.",
    shortDescription: "Larry and Sergey's journey to build Google.",
    season: "Summer 2025",
    episode: "2",
    date: "June 29, 2025",
    coverImage: "/google-original-logo-colorful-1998-retro.jpg",
    youtubeId: "dQw4w9WgXcQ",
    spotifyUrl: "https://open.spotify.com/show/acquired",
    applePodcastsUrl: "https://podcasts.apple.com/podcast/acquired",
  },
  {
    slug: generateSlug("Building the Savannah Bananas"),
    title: "Building the Savannah Bananas (with Jesse Cole)",
    company: "Savannah Bananas",
    duration: "ACQ2",
    description: "How Jesse Cole built the most entertaining team in sports.",
    shortDescription: "Jesse Cole's journey to build the Savannah Bananas.",
    season: "ACQ2",
    episode: "",
    date: "June 15, 2025",
    coverImage: "/savannah-bananas-baseball-yellow-entertainment-jes.jpg",
    youtubeId: "dQw4w9WgXcQ",
    spotifyUrl: "https://open.spotify.com/show/acquired",
    applePodcastsUrl: "https://podcasts.apple.com/podcast/acquired",
  },
  {
    slug: generateSlug("The Steve Ballmer Interview"),
    title: "The Steve Ballmer Interview",
    company: "Steve Ballmer",
    duration: "Summer 2025, Episode 1",
    description: "The former Microsoft CEO and LA Clippers owner on competition and leadership.",
    shortDescription: "Interview with Steve Ballmer on competition and leadership.",
    season: "Summer 2025",
    episode: "1",
    date: "June 1, 2025",
    coverImage: "/steve-ballmer-microsoft-clippers-passionate-speaki.jpg",
    youtubeId: "dQw4w9WgXcQ",
    spotifyUrl: "https://open.spotify.com/show/acquired",
    applePodcastsUrl: "https://podcasts.apple.com/podcast/acquired",
  },
  {
    slug: generateSlug("Undoing a $5 Billion Acquisition and Building a Durable Standalone Plaid"),
    title: "Undoing a $5 Billion Acquisition and Building a Durable Standalone Plaid",
    company: "Plaid",
    duration: "ACQ2",
    description: "Plaid CEO Zach Perret on walking away from Visa and building independently.",
    shortDescription: "Plaid CEO's journey to build a standalone company.",
    season: "ACQ2",
    episode: "",
    date: "May 26, 2025",
    coverImage: "/zach-perret-plaid-ceo-fintech-startup.jpg",
    youtubeId: "dQw4w9WgXcQ",
    spotifyUrl: "https://open.spotify.com/show/acquired",
    applePodcastsUrl: "https://podcasts.apple.com/podcast/acquired",
  },
  {
    slug: generateSlug("Epic Systems (MyChart)"),
    title: "Epic Systems (MyChart)",
    company: "Epic Systems",
    duration: "Spring 2025, Episode 4",
    description: "How Judy Faulkner built healthcare's most important software company.",
    shortDescription: "Judy Faulkner's journey to build Epic Systems.",
    season: "Spring 2025",
    episode: "4",
    date: "April 20, 2025",
    coverImage: "/epic-systems-mychart-healthcare-software-logo.jpg",
    youtubeId: "dQw4w9WgXcQ",
    spotifyUrl: "https://open.spotify.com/show/acquired",
    applePodcastsUrl: "https://podcasts.apple.com/podcast/acquired",
  },
  {
    slug: generateSlug("Indian Premier League Cricket"),
    title: "Indian Premier League Cricket",
    company: "IPL Cricket",
    duration: "Spring 2025, Episode 3",
    description: "How the IPL became the world's richest cricket league.",
    shortDescription: "The IPL's journey to become the world's richest cricket league.",
    season: "Spring 2025",
    episode: "3",
    date: "March 23, 2025",
    coverImage: "/placeholder.svg?height=600&width=400",
    youtubeId: "dQw4w9WgXcQ",
    spotifyUrl: "https://open.spotify.com/show/acquired",
    applePodcastsUrl: "https://podcasts.apple.com/podcast/acquired",
  },
  {
    slug: generateSlug("The Art of Selling Enterprise Software"),
    title: "The Art of Selling Enterprise Software (with ServiceNow CEO Bill McDermott)",
    company: "Bill McDermott",
    duration: "ACQ2",
    description: "The legendary enterprise sales leader on building and selling software.",
    shortDescription: "Bill McDermott on selling enterprise software.",
    season: "ACQ2",
    episode: "",
    date: "March 9, 2025",
    coverImage: "/placeholder.svg?height=600&width=400",
    youtubeId: "dQw4w9WgXcQ",
    spotifyUrl: "https://open.spotify.com/show/acquired",
    applePodcastsUrl: "https://podcasts.apple.com/podcast/acquired",
  },
  {
    slug: generateSlug("Rolex"),
    title: "Rolex",
    company: "Rolex",
    duration: "Spring 2025, Episode 2",
    description: "The story of how a German immigrant created the world's most prestigious watch brand.",
    shortDescription: "The story of Rolex's creation.",
    season: "Spring 2025",
    episode: "2",
    date: "February 23, 2025",
    coverImage: "/placeholder.svg?height=600&width=400",
    youtubeId: "dQw4w9WgXcQ",
    spotifyUrl: "https://open.spotify.com/show/acquired",
    applePodcastsUrl: "https://podcasts.apple.com/podcast/acquired",
  },
  {
    slug: generateSlug("Building Web Apps with Just English and AI"),
    title: "Building Web Apps with Just English and AI (with Vercel CEO Guillermo Rauch)",
    company: "Guillermo Rauch",
    duration: "ACQ2",
    description: "Vercel CEO on the future of web development and AI.",
    shortDescription: "Vercel CEO on web development and AI.",
    season: "ACQ2",
    episode: "",
    date: "February 18, 2025",
    coverImage: "/placeholder.svg?height=600&width=400",
    youtubeId: "dQw4w9WgXcQ",
    spotifyUrl: "https://open.spotify.com/show/acquired",
    applePodcastsUrl: "https://podcasts.apple.com/podcast/acquired",
  },
  {
    slug: generateSlug("TSMC Founder Morris Chang"),
    title: "TSMC Founder Morris Chang",
    company: "Morris Chang",
    duration: "Spring 2025, Episode 1",
    description: "The founder of TSMC on building the world's most important company.",
    shortDescription: "TSMC Founder Morris Chang's story.",
    season: "Spring 2025",
    episode: "1",
    date: "January 26, 2025",
    coverImage: "/placeholder.svg?height=600&width=400",
    youtubeId: "dQw4w9WgXcQ",
    spotifyUrl: "https://open.spotify.com/show/acquired",
    applePodcastsUrl: "https://podcasts.apple.com/podcast/acquired",
  },
  {
    slug: generateSlug("TSMC (Remastered)"),
    title: "TSMC (Remastered)",
    company: "TSMC",
    duration: "Special",
    description: "Our TSMC episode, remastered with new insights and analysis.",
    shortDescription: "Remastered TSMC episode with new insights.",
    season: "Special",
    episode: "",
    date: "January 20, 2025",
    coverImage: "/placeholder.svg?height=600&width=400",
    youtubeId: "dQw4w9WgXcQ",
    spotifyUrl: "https://open.spotify.com/show/acquired",
    applePodcastsUrl: "https://podcasts.apple.com/podcast/acquired",
  },
]

export function getEpisodeBySlug(slug: string): Episode | undefined {
  return allEpisodes.find((ep) => ep.slug === slug)
}
